// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 //import 'firebase_options.dart';
/// // ...
///await Firebase.initializeApp(
///options: DefaultFirebaseOptions.currentPlatform,
///);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiTg0Hts7NB25LJ8rEFjcptQ6PWo1lujc',
    appId: '1:299724839206:web:8a0d520546e7781affc9e7',
    messagingSenderId: '299724839206',
    projectId: 'my-flutter-app-7f455',
    authDomain: 'my-flutter-app-7f455.firebaseapp.com',
    storageBucket: 'my-flutter-app-7f455.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoaxsTlbn7ckRagcjQ5t_5PyS4xLmndXI',
    appId: '1:299724839206:android:c308d822539dd88dffc9e7',
    messagingSenderId: '299724839206',
    projectId: 'my-flutter-app-7f455',
    storageBucket: 'my-flutter-app-7f455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkFIgUF3-wql4S-YvpyJwLXyZWyg_diy4',
    appId: '1:299724839206:ios:1464c9dbba753aafffc9e7',
    messagingSenderId: '299724839206',
    projectId: 'my-flutter-app-7f455',
    storageBucket: 'my-flutter-app-7f455.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkFIgUF3-wql4S-YvpyJwLXyZWyg_diy4',
    appId: '1:299724839206:ios:1464c9dbba753aafffc9e7',
    messagingSenderId: '299724839206',
    projectId: 'my-flutter-app-7f455',
    storageBucket: 'my-flutter-app-7f455.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiTg0Hts7NB25LJ8rEFjcptQ6PWo1lujc',
    appId: '1:299724839206:web:b44987aa8a2612b3ffc9e7',
    messagingSenderId: '299724839206',
    projectId: 'my-flutter-app-7f455',
    authDomain: 'my-flutter-app-7f455.firebaseapp.com',
    storageBucket: 'my-flutter-app-7f455.appspot.com',
  );
}
